name: flutter_boilerplate
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  device_info: 0.4.0
  shared_preferences: ^0.5.3+4
  dio: ^3.0.7
  provider: ^3.1.0
  url_launcher: ^5.1.0
  flutter_screenutil: ^0.6.0
  sentry: ^2.3.1
  package_info: ^0.4.0+10
  connectivity: ^0.4.6
  system_info: ^0.1.1
  json_annotation: ^3.0.0
  flutter_svg: ^0.14.4
  intl: any
  expandable: ^3.0.1
  get_it: ^3.0.3
  firebase_analytics: ^5.0.2
  photo_view: ^0.8.0
  firebase_messaging: ^6.0.1
  cloud_firestore: ^0.12.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  effective_dart: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/langs/

  fonts:
    - family: Muli-Regular
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
